export const customStyles = {
  option: (provided) => ({
    ...provided,
    // padding: "0px",
    background: "transparent",
    border: "none",
    outline: "none",
    fontSize: "18px",
    fontWeight: "400",
    color: "var(--text-rgba)",
    backgroundColor: "transparent",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      color: "#FF868D",
      fontWeight: "400",
    },
    textAlign: "left",
  }),
  control: (styles) => ({
    ...styles,
    fontFamily: "Poppins",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: "normal",
    borderRadius: "8px",
    backgroundColor: "rgba(74, 86, 226, 0.10)",
    border: 0,
    background: "transparent",
    color: "var(--white-600)",
    boxShadow: "none",
    display: "flex",
    flexWrap: "nowrap",
    borderColor: "transparent",
    outline: "transparent",
    padding: "0px",
  }),
  valueContainer: (provided) => ({
    ...provided,
    padding: "0px", // <- Вот это уберёт padding: 2px 8px
  }),
  singleValue: (provided, state) => ({
    ...provided,
    opacity: state.isDisabled ? 0.5 : 1,
    transition: "opacity 300ms",
    right: 5,
    color: "var(--text-color)",
    padding: "0",
  }),
  menu: (provided) => ({
    ...provided,
    background:
      "linear-gradient(0deg,rgba(83, 61, 186, 1) 0%,rgba(80, 48, 154, 1) 36%,rgba(106, 70, 165, 1) 61%,rgba(133, 93, 175, 1) 100%)",
    borderRadius: "8px",
    blur: "5px",
    scrollBar: "none",
    "::-webkit-scrollbar": {
      width: "0px",
      height: "0px",
    },
  }),
  menuList: (base) => ({
    ...base,
    "::-webkit-scrollbar": {
      display: "none",
    },
    scrollbarWidth: "none",
    paddingTop: "0px",
  }),
  indicatorSeparator: () => ({}),
  indicators: () => ({
    cursor: "pointer",
  }),
  input: (provided) => ({
    ...provided,
    margin: "0px",
    color: "var(--text-color)",
    minWidth: "100%",
    caretColor: "transparent",
    padding: "0px",
  }),
  placeholder: (defaultStyles) => ({
    ...defaultStyles,
    fontFamily: "var(--font-family)",
    fontWeight: 400,
    fontSize: "18px",
    color: "var(--white-600)",
    opacity: 1,
  }),
};
